### ISSUE TITLE
Can't make keyboard backlight work

### ISSUE THREAD

**Issue by jeanravin** [digitalec/thinkmac-t470#3]
First, thanks for your guide, it helped me having the sound working. I also had to use [this](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/ALCPlugFix) to fix headphone sound problem.

I'm using AppleBacklightFixup.kext and SSDT-PNLF.aml but it won't work. I suppose I should have some controls in the keyboard prefpane? (or maybe this doesn't have anything to do with the keyboard?)

My T470 is very close to yours. Same processor and graphics. Except I don't have internal battery (only an oversized removable one).

**Comment by digitalec** [comment]
BacklightFixup and SSDT-PNLF are for the display backlight. The keyboard backlight (Fn + Spacebar) seems to be controlled directly through the hardware as I can toggle it prior to loading an OS.

What happens if you toggle the backlight with Fn+Spacebar?

I’ve only used keyboard prefpane to setup gestures for the touchpad. For example, to move between desktops with a three finger swipe, you select it from the list under Shortcuts and when prompted to press a key to set as the new shortcut key, make the gesture on the touchpad.

**Comment by jeanravin** [comment]
Oh, I didn't know about this shortcut. It's working indeed. Thanks.

(didn't know you could use gestures instead of shortcuts either, I'm not very used to laptops, I'll check that)
